import type { GetContentIdeasResponse } from '#/dtos/content-ideas'

export const MOCK_CONTENT_IDEAS: GetContentIdeasResponse = [
  {
    ideaId: 'idea_mock001abc',
    ideaType: 'review',
    category: 'Điện tử',
    targetPlatform: 'tiktok',
    hook: 'Review chuột Bluetooth GOOJODOQ — Nhẹ, êm, giá cực tốt!',
    angle: 'product review',
    productIds: ['prod_uVCh7nXOFGhY'],
    sourceRefs: [],
    priority: 8,
    status: 'draft',
    createdAt: '2026-04-18T06:30:00Z',
    updatedAt: '2026-04-18T06:30:00Z',
  },
  {
    ideaId: 'idea_mock002def',
    ideaType: 'deal',
    category: 'Điện tử',
    targetPlatform: 'facebook',
    hook: 'Deal hot: Tai nghe Sony WH-1000XM5 giảm giá sốc',
    angle: 'price comparison',
    productIds: ['prod_abc123def456'],
    sourceRefs: [],
    priority: 9,
    status: 'approved',
    createdAt: '2026-04-17T10:15:00Z',
    updatedAt: '2026-04-17T12:00:00Z',
  },
  {
    ideaId: 'idea_mock003ghi',
    ideaType: 'review',
    category: 'Phụ kiện',
    targetPlatform: 'instagram',
    hook: 'Sạc dự phòng Anker 20.000mAh — Trọn bộ sạc cả ngày',
    angle: 'lifestyle review',
    productIds: ['prod_xyz789ghi012'],
    sourceRefs: [],
    priority: 6,
    status: 'produced',
    createdAt: '2026-04-16T14:00:00Z',
    updatedAt: '2026-04-16T16:30:00Z',
  },
  {
    ideaId: 'idea_mock004jkl',
    ideaType: 'tutorial',
    category: 'Gia dụng',
    targetPlatform: 'youtube',
    hook: 'Cách dùng máy hút bụi Dyson V12 đúng cách',
    angle: 'how-to guide',
    productIds: ['prod_qrs345tuv678'],
    sourceRefs: [],
    priority: 7,
    status: 'draft',
    owner: 'admin',
    createdAt: '2026-04-14T09:00:00Z',
    updatedAt: '2026-04-15T08:00:00Z',
  },
]

export const MOCK_CONTENT_POSTS: any[] = [
  {
    postId: 'fe960fc0-fd34-48b8-ba8e-3b537c71b908',
    productIds: 'prod_uVCh7nXOFGhY',
    primary_productId: 'prod_uVCh7nXOFGhY',
    contentType: 'review',
    platform: 'facebook',
    title: 'Review Chuột Bluetooth GOOJODOQ — Nhẹ, êm, giá cực tốt',
    body: '**Chuột Bluetooth GOOJODOQ 2.4GHz**\nThương hiệu: GOOJODOQ\n\n## Đánh giá chi tiết\n\n**Thông số chính:**\n- 3 chế độ kết nối: 2.4GHz + 2 Bluetooth\n- Dùng được 2 thiết bị cùng lúc\n- Silent click — cực êm\n- Màn hình LED hiển thị pin\n- 3 mức DPI: 800/1200/1600\n\n⭐ Đánh giá: 4.8/5\n(20 đánh giá)\n\n💰 Giá: 253.420₫\n\nChuột công thái học, thiết kế êm tay, phù hợp cả văn phòng lẫn làm việc từ xa. Giá chỉ 253k cho 3 chế độ kết nối là deal rất hời!',
    hashtags: '#Poko;#ReviewHay;#ChuộtBluetooth;#GOOJODOQ',
    cta_text: 'Mua ngay chuột GOOJODOQ với giá 253k qua link trong bio!',
    image_urls:
      'https://down-vn.img.susercontent.com/file/sg-11134201-7rdy6-m02gfhr1d0gld1',
    status: 'draft',
    generation_source: 'template',
    generation_model: 'template-v1',
    createdAt: '2026-04-18T06:30:00Z',
    updatedAt: '2026-04-18T06:30:00Z',
  },
  {
    postId: 'post_mock001abc',
    productIds: 'prod_uVCh7nXOFGhY',
    contentType: 'review',
    platform: 'tiktok',
    title: 'Review Chuột Bluetooth GOOJODOQ — Nhẹ, êm, giá cực tốt',
    body: '**Chuột Bluetooth GOOJODOQ 2.4GHz**\nThương hiệu: GOOJODOQ\n\n## Đánh giá chi tiết\n\n**Thông số chính:**\n- 3 chế độ kết nối: 2.4GHz + 2 Bluetooth\n- Dùng được 2 thiết bị cùng lúc\n- Silent click — cực êm\n- Màn hình LED hiển thị pin\n- 3 mức DPI: 800/1200/1600\n\n⭐ Đánh giá: 4.8/5\n(20 đánh giá)\n\n💰 Giá: 253.420₫\n\nChuột công thái học, thiết kế êm tay, phù hợp cả văn phòng lẫn làm việc từ xa. Giá chỉ 253k cho 3 chế độ kết nối là deal rất hời!',
    hashtags: '#Poko;#ReviewHay;#ChuộtBluetooth;#GOOJODOQ',
    cta_text: 'Mua ngay chuột GOOJODOQ với giá 253k qua link trong bio!',
    image_urls:
      'https://down-vn.img.susercontent.com/file/sg-11134201-7rdy6-m02gfhr1d0gld1',
    status: 'draft',
    generation_source: 'template',
    generation_model: 'template-v1',
    createdAt: '2026-04-18T06:30:00Z',
    updatedAt: '2026-04-18T06:30:00Z',
  },
  {
    postId: 'post_mock002def',
    productIds: 'prod_abc123def456',
    contentType: 'deal',
    platform: 'facebook',
    title: '🔥 Deal hot: Tai nghe Bluetooth Sony WH-1000XM5',
    body: '**Tai nghe Bluetooth Sony WH-1000XM5**\nThương hiệu: Sony\n\n[Nội dung deal sẽ được AI tạo tại đây]\n\nThông số: Noise Cancelling; Bluetooth 5.2; Pin 30 giờ; 250g; LDAC/AAC/SBC',
    hashtags: '#Poko;#ReviewHay;#TaiNghe;#Sony',
    cta_text:
      'Mua ngay tai nghe Sony WH-1000XM5 với giá tốt nhất qua link trong bio!',
    status: 'approved',
    generation_source: 'template',
    generation_model: 'template-v1',
    createdAt: '2026-04-17T10:15:00Z',
    updatedAt: '2026-04-17T12:00:00Z',
  },
  {
    postId: 'post_mock003ghi',
    productIds: 'prod_xyz789ghi012',
    contentType: 'review',
    platform: 'instagram',
    title: 'Review Sạc dự phòng Anker 20.000mAh — Trọn bộ sạc cả ngày',
    body: '**Sạc dự phòng Anker 20.000mAh**\nThương hiệu: Anker\n\n## Đánh giá chi tiết\n\n**Thông số chính:**\n- 20.000mAh\n- 22.5W fast charging\n- 2 cổng USB-C + 1 USB-A\n- Nhỏ gọn, vừa lòng bàn tay\n\n⭐ Đánh giá: 4.6/5\n(342 đánh giá)\n\n💰 Giá: 490.000₫\n\nSạc dự phòng quốc dân từ Anker, dung lượng lớn sạc được iPhone 15 khoảng 4 lần. Hỗ trợ sạc nhanh 22.5W.',
    hashtags: '#Poko;#ReviewHay;#SạcDựPhòng;#Anker',
    cta_text:
      'Mua ngay sạc dự phòng Anker 20.000mAh với giá tốt nhất qua link trong bio!',
    status: 'queued',
    generation_source: 'template',
    generation_model: 'template-v1',
    createdAt: '2026-04-16T14:00:00Z',
    updatedAt: '2026-04-16T16:30:00Z',
  },
  {
    postId: 'post_mock004jkl',
    productIds: 'prod_qrs345tuv678',
    contentType: 'tutorial',
    platform: 'tiktok',
    title: 'Hướng dẫn sử dụng Máy hút bụi cầm tay Dyson V12',
    body: '**Máy hút bụi cầm tay Dyson V12**\nThương hiệu: Dyson\n\n[Nội dung tutorial sẽ được AI tạo tại đây]\n\nThông số: Công suất 150AW; Pin 60 phút; Màn hình LCD; 5 đầu hút',
    hashtags: '#Poko;#ReviewHay;#MáyHụtBụi;#Dyson',
    cta_text:
      'Mua ngay máy hút bụi Dyson V12 với giá tốt nhất qua link trong bio!',
    status: 'published',
    generation_source: 'ai',
    generation_model: 'gpt-4o',
    createdAt: '2026-04-14T09:00:00Z',
    updatedAt: '2026-04-15T08:00:00Z',
  },
  {
    postId: 'post_mock005mno',
    productIds: 'prod_wxy901zab234',
    contentType: 'trending',
    platform: 'youtube',
    title: 'Xu hướng: Bàn phím cơ Keychron K3 Pro — Mỏng nhất thế giới',
    body: '**Bàn phím cơ Keychron K3 Pro**\nThương hiệu: Keychron\n\n[Nội dung trending sẽ được AI tạo tại đây]\n\nThông số: Low-profile Gateron switch; Bluetooth/2.4GHz/USB-C; RGB; Hot-swappable',
    hashtags: '#Poko;#ReviewHay;#BànPhímCơ;#Keychron',
    cta_text:
      'Mua ngay bàn phím Keychron K3 Pro với giá tốt nhất qua link trong bio!',
    status: 'archived',
    generation_source: 'template',
    generation_model: 'template-v1',
    createdAt: '2026-04-10T11:30:00Z',
    updatedAt: '2026-04-12T09:00:00Z',
  },
]
