/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Affiliate Backend API
 * Monorepo-based NestJS API with modular architecture, Zod validation, and multiple auth strategies.
 * OpenAPI spec version: 1.0
 */

export type _ContentPostDetailDtoType =
  (typeof _ContentPostDetailDtoType)[keyof typeof _ContentPostDetailDtoType]

export const _ContentPostDetailDtoType = {
  detail: 'detail',
} as const
