/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Affiliate Backend API
 * Monorepo-based NestJS API with modular architecture, Zod validation, and multiple auth strategies.
 * OpenAPI spec version: 1.0
 */
import type { AffiliateLinkResponseDtoDeeplinkStatus } from './affiliateLinkResponseDtoDeeplinkStatus'

export interface AffiliateLinkResponseDto {
  linkId: string
  productId: string
  merchant: string
  originalUrl: string
  affiliateUrl: string
  shortUrl?: string
  platform: string
  commissionRate?: number
  couponCode?: string
  deeplinkStatus: AffiliateLinkResponseDtoDeeplinkStatus
  active: boolean
  createdAt: string
}
