/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Affiliate Backend API
 * Monorepo-based NestJS API with modular architecture, Zod validation, and multiple auth strategies.
 * OpenAPI spec version: 1.0
 */

export type AttentionItemDtoType = typeof AttentionItemDtoType[keyof typeof AttentionItemDtoType];


export const AttentionItemDtoType = {
  approved_seed_no_products: 'approved_seed_no_products',
  approved_seed_no_posts: 'approved_seed_no_posts',
  failed_generation: 'failed_generation',
  failed_publish: 'failed_publish',
} as const;
