/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Affiliate Backend API
 * Monorepo-based NestJS API with modular architecture, Zod validation, and multiple auth strategies.
 * OpenAPI spec version: 1.0
 */
import type { ConfigDtoDefaultProps } from './configDtoDefaultProps';
import type { PropertyFieldDto } from './propertyFieldDto';

export interface ConfigDto {
  /** Ordered list of inspector panel fields */
  propertySchema: PropertyFieldDto[];
  /** Default configuration values */
  defaultProps: ConfigDtoDefaultProps;
}
