/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Affiliate Backend API
 * Monorepo-based NestJS API with modular architecture, Zod validation, and multiple auth strategies.
 * OpenAPI spec version: 1.0
 */

export type ContentIdeasControllerListPaginatedSortBy = typeof ContentIdeasControllerListPaginatedSortBy[keyof typeof ContentIdeasControllerListPaginatedSortBy];


export const ContentIdeasControllerListPaginatedSortBy = {
  priority: 'priority',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  status: 'status',
} as const;
