/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Affiliate Backend API
 * Monorepo-based NestJS API with modular architecture, Zod validation, and multiple auth strategies.
 * OpenAPI spec version: 1.0
 */

export interface ContentIdeaResponseDto {
  ideaId: string;
  /** Type of content idea */
  ideaType: string;
  category: string;
  /** Target platform */
  targetPlatform: string;
  /** Main title/hook */
  hook: string;
  /** Content angle */
  angle?: string;
  /** Reference URLs */
  sourceRefs: string[];
  /**
     * @minimum 1
     * @maximum 10
     */
  priority: number;
  /** Idea status */
  status: string;
  owner?: string;
  createdAt: string;
  updatedAt: string;
  /** Associated product UUIDs */
  ideaProducts?: string[];
  /** IDs of posts generated from this idea */
  postIds?: string[];
}
