/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Affiliate Backend API
 * Monorepo-based NestJS API with modular architecture, Zod validation, and multiple auth strategies.
 * OpenAPI spec version: 1.0
 */
import type { _ContentPostSummaryDtoType } from './_contentPostSummaryDtoType';
import type { ContentPostPrimaryProductDto } from './contentPostPrimaryProductDto';

export interface ContentPostSummaryDto {
  _type: _ContentPostSummaryDtoType;
  postId: string;
  title: string;
  platform: string;
  status: string;
  contentType: string;
  createdAt: string;
  updatedAt: string;
  primaryProduct?: ContentPostPrimaryProductDto;
}
