/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Affiliate Backend API
 * Monorepo-based NestJS API with modular architecture, Zod validation, and multiple auth strategies.
 * OpenAPI spec version: 1.0
 */

/**
 * Type of content idea
 */
export type CreateContentIdeaDtoIdeaType = typeof CreateContentIdeaDtoIdeaType[keyof typeof CreateContentIdeaDtoIdeaType];


export const CreateContentIdeaDtoIdeaType = {
  review: 'review',
  comparison: 'comparison',
  roundup: 'roundup',
  tutorial: 'tutorial',
  deal: 'deal',
  trending: 'trending',
} as const;
