/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Affiliate Backend API
 * Monorepo-based NestJS API with modular architecture, Zod validation, and multiple auth strategies.
 * OpenAPI spec version: 1.0
 */
import type { CreateContentIdeaDtoIdeaProductsItem } from './createContentIdeaDtoIdeaProductsItem'
import type { CreateContentIdeaDtoIdeaType } from './createContentIdeaDtoIdeaType'
import type { CreateContentIdeaDtoStatus } from './createContentIdeaDtoStatus'
import type { CreateContentIdeaDtoTargetPlatform } from './createContentIdeaDtoTargetPlatform'

export interface CreateContentIdeaDto {
  /** Type of content idea */
  ideaType: CreateContentIdeaDtoIdeaType
  /** Category */
  category: string
  /** Target platform */
  targetPlatform: CreateContentIdeaDtoTargetPlatform
  /** Main title/hook */
  hook: string
  /** Content angle */
  angle?: string
  /** Associated product UUIDs */
  productIds?: string[]
  /** Reference URLs */
  sourceRefs?: string[]
  /**
   * Priority (1-10)
   * @minimum 1
   * @maximum 10
   */
  priority?: number
  /** Idea status */
  status?: CreateContentIdeaDtoStatus
  /** Owner identifier */
  owner?: string
  /** Associated products with IDs */
  ideaProducts?: CreateContentIdeaDtoIdeaProductsItem[]
}
