/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Affiliate Backend API
 * Monorepo-based NestJS API with modular architecture, Zod validation, and multiple auth strategies.
 * OpenAPI spec version: 1.0
 */
import type { CreateContentPostDtoApprovalStatus } from './createContentPostDtoApprovalStatus';
import type { CreateContentPostDtoContentType } from './createContentPostDtoContentType';
import type { CreateContentPostDtoStatus } from './createContentPostDtoStatus';

export interface CreateContentPostDto {
  /** Content Idea UUID */
  ideaId: string;
  /** Primary Product UUID */
  primaryProductId: string;
  /** Content type */
  contentType: CreateContentPostDtoContentType;
  /** Platform identifier */
  platform: string;
  /** Post title */
  title: string;
  /** Post body/content */
  body: string;
  /** Hashtags for the post */
  hashtags?: string[];
  /** Content status */
  status?: CreateContentPostDtoStatus;
  /** Approval status */
  approvalStatus?: CreateContentPostDtoApprovalStatus;
  /** Generation source identifier */
  generationSource?: string;
  /** AI model used for generation */
  generationModel?: string;
}
