/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Affiliate Backend API
 * Monorepo-based NestJS API with modular architecture, Zod validation, and multiple auth strategies.
 * OpenAPI spec version: 1.0
 */

export interface CreatePublicationDto {
  /**
     * Platform identifier
     * @maxLength 50
     */
  platform?: string;
  /** Target type within the platform */
  targetType?: string;
  /** Platform-specific target ID */
  targetId?: string;
  /** Human-readable target name */
  targetName?: string;
  /** Scheduled publish time (ISO 8601) */
  scheduledFor?: string;
}
