/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Affiliate Backend API
 * Monorepo-based NestJS API with modular architecture, Zod validation, and multiple auth strategies.
 * OpenAPI spec version: 1.0
 */
import type { CreateAffiliateLinkDtoDeeplinkStatus } from './createAffiliateLinkDtoDeeplinkStatus'

export interface CreateAffiliateLinkDto {
  /** Product UUID this link belongs to */
  productId: string
  /** Merchant name */
  merchant: string
  /** Original product URL */
  originalUrl: string
  /** Affiliate tracking URL */
  affiliateUrl: string
  /** Shortened tracking URL */
  shortUrl?: string
  /** Platform identifier */
  platform: string
  /** Commission rate percentage (0-100) */
  commissionRate?: number
  /** Coupon code for this link */
  couponCode?: string
  /** Deeplink status */
  deeplinkStatus: CreateAffiliateLinkDtoDeeplinkStatus
  /** Whether the link is active */
  active?: boolean
}
