/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Affiliate Backend API
 * Monorepo-based NestJS API with modular architecture, Zod validation, and multiple auth strategies.
 * OpenAPI spec version: 1.0
 */

export type DashboardOverviewResponseDtoRange =
  (typeof DashboardOverviewResponseDtoRange)[keyof typeof DashboardOverviewResponseDtoRange]

export const DashboardOverviewResponseDtoRange = {
  '7d': '7d',
  '30d': '30d',
  '90d': '90d',
} as const
