/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Affiliate Backend API
 * Monorepo-based NestJS API with modular architecture, Zod validation, and multiple auth strategies.
 * OpenAPI spec version: 1.0
 */
import type { DisplayWhenDtoValue } from './displayWhenDtoValue'

export interface DisplayWhenDto {
  /** Config key to check */
  key: string
  /** Expected value */
  value: DisplayWhenDtoValue
}
