/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Affiliate Backend API
 * Monorepo-based NestJS API with modular architecture, Zod validation, and multiple auth strategies.
 * OpenAPI spec version: 1.0
 */

/**
 * What triggered this execution
 */
export type ExecuteWorkflowDtoTriggeredBy = typeof ExecuteWorkflowDtoTriggeredBy[keyof typeof ExecuteWorkflowDtoTriggeredBy];


export const ExecuteWorkflowDtoTriggeredBy = {
  manual: 'manual',
  schedule: 'schedule',
} as const;
