/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Affiliate Backend API
 * Monorepo-based NestJS API with modular architecture, Zod validation, and multiple auth strategies.
 * OpenAPI spec version: 1.0
 */

/**
 * Trigger data passed to the workflow (accessible as {{ trigger.* }} or {{ input.* }})
 */
export type ExecuteWorkflowDtoTriggerData = { [key: string]: unknown }
