/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Affiliate Backend API
 * Monorepo-based NestJS API with modular architecture, Zod validation, and multiple auth strategies.
 * OpenAPI spec version: 1.0
 */
import type { ExecuteWorkflowDtoMode } from './executeWorkflowDtoMode'
import type { ExecuteWorkflowDtoTriggerData } from './executeWorkflowDtoTriggerData'
import type { ExecuteWorkflowDtoTriggeredBy } from './executeWorkflowDtoTriggeredBy'

export interface ExecuteWorkflowDto {
  /** Execution mode */
  mode: ExecuteWorkflowDtoMode
  /** Target node ID (required for to-node and single-node modes) */
  targetNodeId?: string
  /** What triggered this execution */
  triggeredBy?: ExecuteWorkflowDtoTriggeredBy
  /** Trigger data passed to the workflow (accessible as {{ trigger.* }} or {{ input.* }}) */
  triggerData?: ExecuteWorkflowDtoTriggerData
}
