/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Affiliate Backend API
 * Monorepo-based NestJS API with modular architecture, Zod validation, and multiple auth strategies.
 * OpenAPI spec version: 1.0
 */
import type { GenerateContentPostsDtoContentType } from './generateContentPostsDtoContentType'

export interface GenerateContentPostsDto {
  /** Product UUIDs to generate posts for */
  productIds: string[]
  /** Content type */
  contentType: GenerateContentPostsDtoContentType
  /** Platform identifier */
  platform: string
}
