/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Affiliate Backend API
 * Monorepo-based NestJS API with modular architecture, Zod validation, and multiple auth strategies.
 * OpenAPI spec version: 1.0
 */

/**
 * Target platform
 */
export type GenerateIdeasDtoPlatform = typeof GenerateIdeasDtoPlatform[keyof typeof GenerateIdeasDtoPlatform];


export const GenerateIdeasDtoPlatform = {
  facebook: 'facebook',
  tiktok: 'tiktok',
  instagram: 'instagram',
  youtube: 'youtube',
  blog: 'blog',
} as const;
