/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Affiliate Backend API
 * Monorepo-based NestJS API with modular architecture, Zod validation, and multiple auth strategies.
 * OpenAPI spec version: 1.0
 */
import type { HealthControllerCheck200Details } from './healthControllerCheck200Details';
import type { HealthControllerCheck200Error } from './healthControllerCheck200Error';
import type { HealthControllerCheck200Info } from './healthControllerCheck200Info';

export type HealthControllerCheck200 = {
  status?: string;
  /** @nullable */
  info?: HealthControllerCheck200Info;
  /** @nullable */
  error?: HealthControllerCheck200Error;
  details?: HealthControllerCheck200Details;
};
