/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Affiliate Backend API
 * Monorepo-based NestJS API with modular architecture, Zod validation, and multiple auth strategies.
 * OpenAPI spec version: 1.0
 */
import type { HealthControllerCheck503Details } from './healthControllerCheck503Details';
import type { HealthControllerCheck503Error } from './healthControllerCheck503Error';
import type { HealthControllerCheck503Info } from './healthControllerCheck503Info';

export type HealthControllerCheck503 = {
  status?: string;
  /** @nullable */
  info?: HealthControllerCheck503Info;
  /** @nullable */
  error?: HealthControllerCheck503Error;
  details?: HealthControllerCheck503Details;
};
