/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Affiliate Backend API
 * Monorepo-based NestJS API with modular architecture, Zod validation, and multiple auth strategies.
 * OpenAPI spec version: 1.0
 */
import type { IdentityDtoCategory } from './identityDtoCategory';
import type { IdentityDtoKind } from './identityDtoKind';

export interface IdentityDto {
  /** Immutable node type identifier (namespace.name) */
  typeId: string;
  /** Schema version */
  version: number;
  /** Node execution kind */
  kind: IdentityDtoKind;
  /** UI grouping category */
  category: IdentityDtoCategory;
  /** Display name on canvas */
  title: string;
  /** Tooltip text in palette */
  description: string;
  /** Icon key from design system */
  icon?: string;
  /** Search keywords for palette */
  tags?: string[];
  /** If true, hidden from palette but still executable */
  deprecated?: boolean;
  /** Successor node typeId when deprecated=true */
  replacementTypeId?: string;
  /** If true, only available as agent tool, not in main palette */
  supportingOnly?: boolean;
}
