/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Affiliate Backend API
 * Monorepo-based NestJS API with modular architecture, Zod validation, and multiple auth strategies.
 * OpenAPI spec version: 1.0
 */

/**
 * Node execution kind
 */
export type IdentityDtoKind = typeof IdentityDtoKind[keyof typeof IdentityDtoKind];


export const IdentityDtoKind = {
  execution: 'execution',
  resource: 'resource',
  agent: 'agent',
} as const;
