/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Affiliate Backend API
 * Monorepo-based NestJS API with modular architecture, Zod validation, and multiple auth strategies.
 * OpenAPI spec version: 1.0
 */

/**
 * UI grouping category
 */
export type IdentityDtoCategory =
  (typeof IdentityDtoCategory)[keyof typeof IdentityDtoCategory]

export const IdentityDtoCategory = {
  trigger: 'trigger',
  logic: 'logic',
  data: 'data',
  io: 'io',
  resource: 'resource',
  agent: 'agent',
  crawl: 'crawl',
  db: 'db',
  content: 'content',
  utility: 'utility',
  publish: 'publish',
  affiliate: 'affiliate',
  product: 'product',
} as const
