/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Affiliate Backend API
 * Monorepo-based NestJS API with modular architecture, Zod validation, and multiple auth strategies.
 * OpenAPI spec version: 1.0
 */
import type { ConfigDto } from './configDto';
import type { IdentityDto } from './identityDto';
import type { IODto } from './iODto';
import type { LimitsDto } from './limitsDto';
import type { NodeDefinitionDtoExecution } from './nodeDefinitionDtoExecution';
import type { RetryDto } from './retryDto';
import type { SecurityDto } from './securityDto';
import type { UIDto } from './uIDto';

export interface NodeDefinitionDto {
  identity: IdentityDto;
  io: IODto;
  /** Execution config (discriminated by mode) */
  execution: NodeDefinitionDtoExecution;
  config: ConfigDto;
  limits: LimitsDto;
  retry: RetryDto;
  ui: UIDto;
  security?: SecurityDto;
  builtIn?: boolean;
}
