/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Affiliate Backend API
 * Monorepo-based NestJS API with modular architecture, Zod validation, and multiple auth strategies.
 * OpenAPI spec version: 1.0
 */

export interface PaginationMetaDto {
  total_records: number;
  current_page: number;
  total_pages: number;
  next_page?: number;
  prev_page?: number;
}
