/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Affiliate Backend API
 * Monorepo-based NestJS API with modular architecture, Zod validation, and multiple auth strategies.
 * OpenAPI spec version: 1.0
 */

/**
 * Content status
 */
export type PatchContentPostDtoStatus =
  (typeof PatchContentPostDtoStatus)[keyof typeof PatchContentPostDtoStatus]

export const PatchContentPostDtoStatus = {
  draft: 'draft',
  approved: 'approved',
  queued: 'queued',
  published: 'published',
  archived: 'archived',
} as const
