/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Affiliate Backend API
 * Monorepo-based NestJS API with modular architecture, Zod validation, and multiple auth strategies.
 * OpenAPI spec version: 1.0
 */

/**
 * Content type
 */
export type PatchContentPostDtoContentType = typeof PatchContentPostDtoContentType[keyof typeof PatchContentPostDtoContentType];


export const PatchContentPostDtoContentType = {
  review: 'review',
  comparison: 'comparison',
  roundup: 'roundup',
  tutorial: 'tutorial',
  deal: 'deal',
  trending: 'trending',
} as const;
