/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Affiliate Backend API
 * Monorepo-based NestJS API with modular architecture, Zod validation, and multiple auth strategies.
 * OpenAPI spec version: 1.0
 */

/**
 * Typed data format
 */
export type PortDtoDataType =
  (typeof PortDtoDataType)[keyof typeof PortDtoDataType]

export const PortDtoDataType = {
  string: 'string',
  number: 'number',
  boolean: 'boolean',
  object: 'object',
  array: 'array',
  'array<object>': 'array<object>',
  any: 'any',
} as const
