/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Affiliate Backend API
 * Monorepo-based NestJS API with modular architecture, Zod validation, and multiple auth strategies.
 * OpenAPI spec version: 1.0
 */
import type { PortDefinitionDtoType } from './portDefinitionDtoType';

export interface PortDefinitionDto {
  /** Unique port identifier on the node */
  id: string;
  /** Human-readable port label */
  label: string;
  /** Port direction */
  type: PortDefinitionDtoType;
  /** Expected data type for this port */
  dataType?: string;
  /** Whether this port must be connected */
  required?: boolean;
}
