/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Affiliate Backend API
 * Monorepo-based NestJS API with modular architecture, Zod validation, and multiple auth strategies.
 * OpenAPI spec version: 1.0
 */

/**
 * Edge rendering type
 */
export type PortDtoEdgeType =
  (typeof PortDtoEdgeType)[keyof typeof PortDtoEdgeType]

export const PortDtoEdgeType = {
  main: 'main',
  error: 'error',
  condition_true: 'condition_true',
  condition_false: 'condition_false',
  reference: 'reference',
} as const
