/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Affiliate Backend API
 * Monorepo-based NestJS API with modular architecture, Zod validation, and multiple auth strategies.
 * OpenAPI spec version: 1.0
 */
import type { PortDtoDataType } from './portDtoDataType'
import type { PortDtoEdgeType } from './portDtoEdgeType'
import type { PortDtoSchema } from './portDtoSchema'

export interface PortDto {
  /** Port identifier used in edge routing */
  id: string
  /** Display label on canvas */
  label: string
  /** Typed data format */
  dataType: PortDtoDataType
  /** If true, connection is required */
  required?: boolean
  /** Edge rendering type */
  edgeType: PortDtoEdgeType
  /** Optional JSON Schema for deep runtime data validation */
  schema?: PortDtoSchema
}
