/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Affiliate Backend API
 * Monorepo-based NestJS API with modular architecture, Zod validation, and multiple auth strategies.
 * OpenAPI spec version: 1.0
 */
import type { PostPublicationDetailDtoErrorCode } from './postPublicationDetailDtoErrorCode'
import type { PostPublicationDetailDtoErrorMessage } from './postPublicationDetailDtoErrorMessage'
import type { PostPublicationDetailDtoExternalPostId } from './postPublicationDetailDtoExternalPostId'
import type { PostPublicationDetailDtoExternalUrl } from './postPublicationDetailDtoExternalUrl'
import type { PostPublicationDetailDtoPublishedAt } from './postPublicationDetailDtoPublishedAt'
import type { PostPublicationDetailDtoPublishStatus } from './postPublicationDetailDtoPublishStatus'
import type { PostPublicationDetailDtoRequestPayload } from './postPublicationDetailDtoRequestPayload'
import type { PostPublicationDetailDtoResponsePayload } from './postPublicationDetailDtoResponsePayload'
import type { PostPublicationDetailDtoScheduledFor } from './postPublicationDetailDtoScheduledFor'
import type { PostPublicationDetailDtoTargetId } from './postPublicationDetailDtoTargetId'
import type { PostPublicationDetailDtoTargetName } from './postPublicationDetailDtoTargetName'
import type { PostPublicationDetailDtoTargetType } from './postPublicationDetailDtoTargetType'

export interface PostPublicationDetailDto {
  publicationId: string
  postId: string
  platform: string
  /** @nullable */
  targetType?: PostPublicationDetailDtoTargetType
  /** @nullable */
  targetId?: PostPublicationDetailDtoTargetId
  /** @nullable */
  targetName?: PostPublicationDetailDtoTargetName
  publishStatus: PostPublicationDetailDtoPublishStatus
  /** @nullable */
  externalPostId?: PostPublicationDetailDtoExternalPostId
  /** @nullable */
  externalUrl?: PostPublicationDetailDtoExternalUrl
  /** @nullable */
  scheduledFor?: PostPublicationDetailDtoScheduledFor
  /** @nullable */
  publishedAt?: PostPublicationDetailDtoPublishedAt
  /** @nullable */
  errorCode?: PostPublicationDetailDtoErrorCode
  /** @nullable */
  errorMessage?: PostPublicationDetailDtoErrorMessage
  createdAt: string
  updatedAt: string
  /** @nullable */
  requestPayload: PostPublicationDetailDtoRequestPayload
  /** @nullable */
  responsePayload: PostPublicationDetailDtoResponsePayload
  /** @nullable */
  externalMediaIds: string[] | null
}
