/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Affiliate Backend API
 * Monorepo-based NestJS API with modular architecture, Zod validation, and multiple auth strategies.
 * OpenAPI spec version: 1.0
 */

export type PostPublicationDetailDtoPublishStatus = typeof PostPublicationDetailDtoPublishStatus[keyof typeof PostPublicationDetailDtoPublishStatus];


export const PostPublicationDetailDtoPublishStatus = {
  pending: 'pending',
  publishing: 'publishing',
  published: 'published',
  failed: 'failed',
  cancelled: 'cancelled',
} as const;
