/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Affiliate Backend API
 * Monorepo-based NestJS API with modular architecture, Zod validation, and multiple auth strategies.
 * OpenAPI spec version: 1.0
 */
import type { PostPublicationSummaryDtoErrorCode } from './postPublicationSummaryDtoErrorCode';
import type { PostPublicationSummaryDtoErrorMessage } from './postPublicationSummaryDtoErrorMessage';
import type { PostPublicationSummaryDtoExternalPostId } from './postPublicationSummaryDtoExternalPostId';
import type { PostPublicationSummaryDtoExternalUrl } from './postPublicationSummaryDtoExternalUrl';
import type { PostPublicationSummaryDtoPublishedAt } from './postPublicationSummaryDtoPublishedAt';
import type { PostPublicationSummaryDtoPublishStatus } from './postPublicationSummaryDtoPublishStatus';
import type { PostPublicationSummaryDtoScheduledFor } from './postPublicationSummaryDtoScheduledFor';
import type { PostPublicationSummaryDtoTargetId } from './postPublicationSummaryDtoTargetId';
import type { PostPublicationSummaryDtoTargetName } from './postPublicationSummaryDtoTargetName';
import type { PostPublicationSummaryDtoTargetType } from './postPublicationSummaryDtoTargetType';

export interface PostPublicationSummaryDto {
  publicationId: string;
  postId: string;
  platform: string;
  /** @nullable */
  targetType?: PostPublicationSummaryDtoTargetType;
  /** @nullable */
  targetId?: PostPublicationSummaryDtoTargetId;
  /** @nullable */
  targetName?: PostPublicationSummaryDtoTargetName;
  publishStatus: PostPublicationSummaryDtoPublishStatus;
  /** @nullable */
  externalPostId?: PostPublicationSummaryDtoExternalPostId;
  /** @nullable */
  externalUrl?: PostPublicationSummaryDtoExternalUrl;
  /** @nullable */
  scheduledFor?: PostPublicationSummaryDtoScheduledFor;
  /** @nullable */
  publishedAt?: PostPublicationSummaryDtoPublishedAt;
  /** @nullable */
  errorCode?: PostPublicationSummaryDtoErrorCode;
  /** @nullable */
  errorMessage?: PostPublicationSummaryDtoErrorMessage;
  createdAt: string;
  updatedAt: string;
}
