/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Affiliate Backend API
 * Monorepo-based NestJS API with modular architecture, Zod validation, and multiple auth strategies.
 * OpenAPI spec version: 1.0
 */

export interface ProductSummaryResponseDto {
  productId: string;
  canonicalTitle: string;
  brand?: string;
  category: string;
  imageCover?: string;
  priceCurrent?: string;
  priceSale?: string;
  rating?: number;
  dealScore: number;
  publishScore: number;
  status: string;
  createdAt: string;
  updatedAt: string;
}
