/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Affiliate Backend API
 * Monorepo-based NestJS API with modular architecture, Zod validation, and multiple auth strategies.
 * OpenAPI spec version: 1.0
 */

export type PromptResponseDtoCategory =
  (typeof PromptResponseDtoCategory)[keyof typeof PromptResponseDtoCategory]

export const PromptResponseDtoCategory = {
  social_media: 'social_media',
  blog: 'blog',
  video: 'video',
  email: 'email',
  general: 'general',
} as const
