/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Affiliate Backend API
 * Monorepo-based NestJS API with modular architecture, Zod validation, and multiple auth strategies.
 * OpenAPI spec version: 1.0
 */

export type PromptResponseDtoPromptType = typeof PromptResponseDtoPromptType[keyof typeof PromptResponseDtoPromptType];


export const PromptResponseDtoPromptType = {
  content_generation: 'content_generation',
  analysis: 'analysis',
  refinement: 'refinement',
  custom: 'custom',
} as const;
