/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Affiliate Backend API
 * Monorepo-based NestJS API with modular architecture, Zod validation, and multiple auth strategies.
 * OpenAPI spec version: 1.0
 */

/**
 * Input widget type for the property
 */
export type PropertySchemaDtoType = typeof PropertySchemaDtoType[keyof typeof PropertySchemaDtoType];


export const PropertySchemaDtoType = {
  string: 'string',
  number: 'number',
  boolean: 'boolean',
  text: 'text',
  json: 'json',
  url: 'url',
  cron: 'cron',
  enum: 'enum',
  select: 'select',
  keyValue: 'keyValue',
  assignments: 'assignments',
} as const;
