/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Affiliate Backend API
 * Monorepo-based NestJS API with modular architecture, Zod validation, and multiple auth strategies.
 * OpenAPI spec version: 1.0
 */
import type { PropertySchemaDtoDefault } from './propertySchemaDtoDefault';
import type { PropertySchemaDtoType } from './propertySchemaDtoType';
import type { PropertySchemaOptionDto } from './propertySchemaOptionDto';

export interface PropertySchemaDto {
  /** Config key stored in node props */
  key: string;
  /** Label shown in the property panel */
  label: string;
  /** Input widget type for the property */
  type: PropertySchemaDtoType;
  /** Whether this field is required */
  required?: boolean;
  /** Default value */
  default?: PropertySchemaDtoDefault;
  /** Available options for enum/select types */
  options?: PropertySchemaOptionDto[];
  /** Minimum value (number type) */
  min?: number;
  /** Maximum value (number type) */
  max?: number;
  /** Placeholder text */
  placeholder?: string;
}
