/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Affiliate Backend API
 * Monorepo-based NestJS API with modular architecture, Zod validation, and multiple auth strategies.
 * OpenAPI spec version: 1.0
 */

/**
 * Input widget type
 */
export type PropertyFieldDtoType = typeof PropertyFieldDtoType[keyof typeof PropertyFieldDtoType];


export const PropertyFieldDtoType = {
  string: 'string',
  number: 'number',
  boolean: 'boolean',
  select: 'select',
  multiselect: 'multiselect',
  url: 'url',
  json: 'json',
  code: 'code',
  secret: 'secret',
  array: 'array',
  text: 'text',
  enum: 'enum',
  cron: 'cron',
  conditions: 'conditions',
  assignments: 'assignments',
  keyValue: 'keyValue',
} as const;
