/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Affiliate Backend API
 * Monorepo-based NestJS API with modular architecture, Zod validation, and multiple auth strategies.
 * OpenAPI spec version: 1.0
 */
import type { RecordPublishFailureDtoResponsePayload } from './recordPublishFailureDtoResponsePayload';

export interface RecordPublishFailureDto {
  /** Platform-specific error code */
  errorCode?: string;
  /** Human-readable error message from the platform */
  errorMessage: string;
  /** Full error response payload from the platform API */
  responsePayload?: RecordPublishFailureDtoResponsePayload;
}
