/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Affiliate Backend API
 * Monorepo-based NestJS API with modular architecture, Zod validation, and multiple auth strategies.
 * OpenAPI spec version: 1.0
 */

export interface ScheduleWorkflowDto {
  /**
   * Cron expression (e.g. "0 *\/6 * * *")
   * @maxLength 100
   */
  cronExpression: string
  /**
   * IANA timezone (e.g. "Asia/Ho_Chi_Minh")
   * @maxLength 64
   */
  timezone: string
  /** Whether the schedule is active */
  enabled?: boolean
}
