/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Affiliate Backend API
 * Monorepo-based NestJS API with modular architecture, Zod validation, and multiple auth strategies.
 * OpenAPI spec version: 1.0
 */

export type ScheduledJobResponseDtoStatus =
  (typeof ScheduledJobResponseDtoStatus)[keyof typeof ScheduledJobResponseDtoStatus]

export const ScheduledJobResponseDtoStatus = {
  pending: 'pending',
  scheduled: 'scheduled',
  published: 'published',
  failed: 'failed',
  cancelled: 'cancelled',
} as const
