/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Affiliate Backend API
 * Monorepo-based NestJS API with modular architecture, Zod validation, and multiple auth strategies.
 * OpenAPI spec version: 1.0
 */

export interface SecurityDto {
  /** If false, node runs in network-isolated worker */
  allowNetwork: boolean;
  /** Secret key names this node may read */
  allowSecrets: string[];
  /** Workspace permissions checked before job enqueue */
  requiredPermissions: string[];
}
