/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Affiliate Backend API
 * Monorepo-based NestJS API with modular architecture, Zod validation, and multiple auth strategies.
 * OpenAPI spec version: 1.0
 */
import type { TrendPointDto } from './trendPointDto';

export interface TrendSeriesDto {
  key: string;
  label: string;
  data: TrendPointDto[];
}
