/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Affiliate Backend API
 * Monorepo-based NestJS API with modular architecture, Zod validation, and multiple auth strategies.
 * OpenAPI spec version: 1.0
 */
import type { SummaryFieldDto } from './summaryFieldDto';
import type { UIDtoColor } from './uIDtoColor';

export interface UIDto {
  /** Node accent color on canvas */
  color: UIDtoColor;
  /** Fields shown on collapsed node card */
  summaryFields: SummaryFieldDto[];
  /** Documentation link */
  helpUrl?: string;
}
