/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Affiliate Backend API
 * Monorepo-based NestJS API with modular architecture, Zod validation, and multiple auth strategies.
 * OpenAPI spec version: 1.0
 */

/**
 * Node accent color on canvas
 */
export type UIDtoColor = typeof UIDtoColor[keyof typeof UIDtoColor];


export const UIDtoColor = {
  purple: 'purple',
  teal: 'teal',
  coral: 'coral',
  pink: 'pink',
  blue: 'blue',
  green: 'green',
  amber: 'amber',
  red: 'red',
  gray: 'gray',
} as const;
