/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Affiliate Backend API
 * Monorepo-based NestJS API with modular architecture, Zod validation, and multiple auth strategies.
 * OpenAPI spec version: 1.0
 */

/**
 * Idea status
 */
export type UpdateContentIdeaDtoStatus =
  (typeof UpdateContentIdeaDtoStatus)[keyof typeof UpdateContentIdeaDtoStatus]

export const UpdateContentIdeaDtoStatus = {
  draft: 'draft',
  approved: 'approved',
  queued: 'queued',
  produced: 'produced',
  rejected: 'rejected',
} as const
