/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Affiliate Backend API
 * Monorepo-based NestJS API with modular architecture, Zod validation, and multiple auth strategies.
 * OpenAPI spec version: 1.0
 */

/**
 * New content status
 */
export type UpdateContentPostStatusDtoStatus = typeof UpdateContentPostStatusDtoStatus[keyof typeof UpdateContentPostStatusDtoStatus];


export const UpdateContentPostStatusDtoStatus = {
  draft: 'draft',
  approved: 'approved',
  queued: 'queued',
  published: 'published',
  archived: 'archived',
} as const;
