/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Affiliate Backend API
 * Monorepo-based NestJS API with modular architecture, Zod validation, and multiple auth strategies.
 * OpenAPI spec version: 1.0
 */

/**
 * Commission rate percentage (0-100)
 */
export type UpdateAffiliateLinkDtoCommissionRate = { [key: string]: unknown }
