/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Affiliate Backend API
 * Monorepo-based NestJS API with modular architecture, Zod validation, and multiple auth strategies.
 * OpenAPI spec version: 1.0
 */
import type { UpdateAffiliateLinkDtoActive } from './updateAffiliateLinkDtoActive'
import type { UpdateAffiliateLinkDtoAffiliateUrl } from './updateAffiliateLinkDtoAffiliateUrl'
import type { UpdateAffiliateLinkDtoCommissionRate } from './updateAffiliateLinkDtoCommissionRate'
import type { UpdateAffiliateLinkDtoCouponCode } from './updateAffiliateLinkDtoCouponCode'
import type { UpdateAffiliateLinkDtoDeeplinkStatus } from './updateAffiliateLinkDtoDeeplinkStatus'
import type { UpdateAffiliateLinkDtoMerchant } from './updateAffiliateLinkDtoMerchant'
import type { UpdateAffiliateLinkDtoOriginalUrl } from './updateAffiliateLinkDtoOriginalUrl'
import type { UpdateAffiliateLinkDtoPlatform } from './updateAffiliateLinkDtoPlatform'
import type { UpdateAffiliateLinkDtoShortUrl } from './updateAffiliateLinkDtoShortUrl'

export interface UpdateAffiliateLinkDto {
  /** Merchant name */
  merchant?: UpdateAffiliateLinkDtoMerchant
  /** Original product URL */
  originalUrl?: UpdateAffiliateLinkDtoOriginalUrl
  /** Affiliate tracking URL */
  affiliateUrl?: UpdateAffiliateLinkDtoAffiliateUrl
  /** Shortened tracking URL */
  shortUrl?: UpdateAffiliateLinkDtoShortUrl
  /** Platform identifier */
  platform?: UpdateAffiliateLinkDtoPlatform
  /** Commission rate percentage (0-100) */
  commissionRate?: UpdateAffiliateLinkDtoCommissionRate
  /** Coupon code for this link */
  couponCode?: UpdateAffiliateLinkDtoCouponCode
  /** Deeplink status */
  deeplinkStatus?: UpdateAffiliateLinkDtoDeeplinkStatus
  /** Whether the link is active */
  active?: UpdateAffiliateLinkDtoActive
}
