/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Affiliate Backend API
 * Monorepo-based NestJS API with modular architecture, Zod validation, and multiple auth strategies.
 * OpenAPI spec version: 1.0
 */

/**
 * Deeplink status
 */
export type UpdateAffiliateLinkDtoDeeplinkStatus = typeof UpdateAffiliateLinkDtoDeeplinkStatus[keyof typeof UpdateAffiliateLinkDtoDeeplinkStatus];


export const UpdateAffiliateLinkDtoDeeplinkStatus = {
  valid: 'valid',
  broken: 'broken',
  pending: 'pending',
  expired: 'expired',
} as const;
