/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Affiliate Backend API
 * Monorepo-based NestJS API with modular architecture, Zod validation, and multiple auth strategies.
 * OpenAPI spec version: 1.0
 */

export interface WorkflowRunDto {
  id: string
  workflow_id: string
  status: string
  started_at: string
  finished_at?: string
  triggered_by?: string
}
