/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Affiliate Backend API
 * Monorepo-based NestJS API with modular architecture, Zod validation, and multiple auth strategies.
 * OpenAPI spec version: 1.0
 */

/**
 * Edge routing type: main for normal flow, error for error path
 */
export type WorkflowEdgeInputDtoEdgeType =
  (typeof WorkflowEdgeInputDtoEdgeType)[keyof typeof WorkflowEdgeInputDtoEdgeType]

export const WorkflowEdgeInputDtoEdgeType = {
  main: 'main',
  error: 'error',
} as const
