/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Affiliate Backend API
 * Monorepo-based NestJS API with modular architecture, Zod validation, and multiple auth strategies.
 * OpenAPI spec version: 1.0
 */
import type { WorkflowVersionDtoMessage } from './workflowVersionDtoMessage';
import type { WorkflowVersionDtoVersionType } from './workflowVersionDtoVersionType';

export interface WorkflowVersionDto {
  id: string;
  version_number: number;
  message?: WorkflowVersionDtoMessage;
  version_type: WorkflowVersionDtoVersionType;
  created_at: string;
}
