/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Affiliate Backend API
 * Monorepo-based NestJS API with modular architecture, Zod validation, and multiple auth strategies.
 * OpenAPI spec version: 1.0
 */
import type { WorkflowNodeInputDtoConfig } from './workflowNodeInputDtoConfig';

export interface WorkflowNodeInputDto {
  xyflow_id: string;
  type: string;
  node_type_id: string;
  position_x: number;
  position_y: number;
  title?: string;
  subtitle?: string;
  icon?: string;
  config?: WorkflowNodeInputDtoConfig;
}
