/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashRouteImport } from './routes/dash'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashIndexRouteImport } from './routes/dash/index'
import { Route as DashSettingsRouteImport } from './routes/dash/settings'
import { Route as DashScheduleRouteImport } from './routes/dash/schedule'
import { Route as DashPromptsRouteImport } from './routes/dash/prompts'
import { Route as DashPagesRouteImport } from './routes/dash/pages'
import { Route as DashContentRouteImport } from './routes/dash/content'
import { Route as DashAnalyticsRouteImport } from './routes/dash/analytics'
import { Route as DashProductsIndexRouteImport } from './routes/dash/products/index'
import { Route as DashPostsIndexRouteImport } from './routes/dash/posts/index'
import { Route as DashContentIndexRouteImport } from './routes/dash/content/index'
import { Route as DashProductsManualImportRouteImport } from './routes/dash/products/manual-import'
import { Route as DashProductsProductIdRouteImport } from './routes/dash/products/$productId'
import { Route as DashPostsScheduledRouteImport } from './routes/dash/posts/scheduled'
import { Route as DashPostsNewRouteImport } from './routes/dash/posts/new'
import { Route as DashContentNewRouteImport } from './routes/dash/content/new'
import { Route as DashContentIdeaIdRouteImport } from './routes/dash/content/$ideaId'
import { Route as DashPostsPostIdIndexRouteImport } from './routes/dash/posts/$postId/index'
import { Route as DashPostsPostIdEditRouteImport } from './routes/dash/posts/$postId/edit'
import { Route as DashContentIdeaIdEditRouteImport } from './routes/dash/content/$ideaId/edit'

const DashRoute = DashRouteImport.update({
  id: '/dash',
  path: '/dash',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashIndexRoute = DashIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashRoute,
} as any)
const DashSettingsRoute = DashSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashRoute,
} as any)
const DashScheduleRoute = DashScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => DashRoute,
} as any)
const DashPromptsRoute = DashPromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => DashRoute,
} as any)
const DashPagesRoute = DashPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => DashRoute,
} as any)
const DashContentRoute = DashContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => DashRoute,
} as any)
const DashAnalyticsRoute = DashAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashRoute,
} as any)
const DashProductsIndexRoute = DashProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => DashRoute,
} as any)
const DashPostsIndexRoute = DashPostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => DashRoute,
} as any)
const DashContentIndexRoute = DashContentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashContentRoute,
} as any)
const DashProductsManualImportRoute =
  DashProductsManualImportRouteImport.update({
    id: '/products/manual-import',
    path: '/products/manual-import',
    getParentRoute: () => DashRoute,
  } as any)
const DashProductsProductIdRoute = DashProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => DashRoute,
} as any)
const DashPostsScheduledRoute = DashPostsScheduledRouteImport.update({
  id: '/posts/scheduled',
  path: '/posts/scheduled',
  getParentRoute: () => DashRoute,
} as any)
const DashPostsNewRoute = DashPostsNewRouteImport.update({
  id: '/posts/new',
  path: '/posts/new',
  getParentRoute: () => DashRoute,
} as any)
const DashContentNewRoute = DashContentNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DashContentRoute,
} as any)
const DashContentIdeaIdRoute = DashContentIdeaIdRouteImport.update({
  id: '/$ideaId',
  path: '/$ideaId',
  getParentRoute: () => DashContentRoute,
} as any)
const DashPostsPostIdIndexRoute = DashPostsPostIdIndexRouteImport.update({
  id: '/posts/$postId/',
  path: '/posts/$postId/',
  getParentRoute: () => DashRoute,
} as any)
const DashPostsPostIdEditRoute = DashPostsPostIdEditRouteImport.update({
  id: '/posts/$postId/edit',
  path: '/posts/$postId/edit',
  getParentRoute: () => DashRoute,
} as any)
const DashContentIdeaIdEditRoute = DashContentIdeaIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => DashContentIdeaIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dash': typeof DashRouteWithChildren
  '/dash/analytics': typeof DashAnalyticsRoute
  '/dash/content': typeof DashContentRouteWithChildren
  '/dash/pages': typeof DashPagesRoute
  '/dash/prompts': typeof DashPromptsRoute
  '/dash/schedule': typeof DashScheduleRoute
  '/dash/settings': typeof DashSettingsRoute
  '/dash/': typeof DashIndexRoute
  '/dash/content/$ideaId': typeof DashContentIdeaIdRouteWithChildren
  '/dash/content/new': typeof DashContentNewRoute
  '/dash/posts/new': typeof DashPostsNewRoute
  '/dash/posts/scheduled': typeof DashPostsScheduledRoute
  '/dash/products/$productId': typeof DashProductsProductIdRoute
  '/dash/products/manual-import': typeof DashProductsManualImportRoute
  '/dash/content/': typeof DashContentIndexRoute
  '/dash/posts/': typeof DashPostsIndexRoute
  '/dash/products/': typeof DashProductsIndexRoute
  '/dash/content/$ideaId/edit': typeof DashContentIdeaIdEditRoute
  '/dash/posts/$postId/edit': typeof DashPostsPostIdEditRoute
  '/dash/posts/$postId/': typeof DashPostsPostIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dash/analytics': typeof DashAnalyticsRoute
  '/dash/pages': typeof DashPagesRoute
  '/dash/prompts': typeof DashPromptsRoute
  '/dash/schedule': typeof DashScheduleRoute
  '/dash/settings': typeof DashSettingsRoute
  '/dash': typeof DashIndexRoute
  '/dash/content/$ideaId': typeof DashContentIdeaIdRouteWithChildren
  '/dash/content/new': typeof DashContentNewRoute
  '/dash/posts/new': typeof DashPostsNewRoute
  '/dash/posts/scheduled': typeof DashPostsScheduledRoute
  '/dash/products/$productId': typeof DashProductsProductIdRoute
  '/dash/products/manual-import': typeof DashProductsManualImportRoute
  '/dash/content': typeof DashContentIndexRoute
  '/dash/posts': typeof DashPostsIndexRoute
  '/dash/products': typeof DashProductsIndexRoute
  '/dash/content/$ideaId/edit': typeof DashContentIdeaIdEditRoute
  '/dash/posts/$postId/edit': typeof DashPostsPostIdEditRoute
  '/dash/posts/$postId': typeof DashPostsPostIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dash': typeof DashRouteWithChildren
  '/dash/analytics': typeof DashAnalyticsRoute
  '/dash/content': typeof DashContentRouteWithChildren
  '/dash/pages': typeof DashPagesRoute
  '/dash/prompts': typeof DashPromptsRoute
  '/dash/schedule': typeof DashScheduleRoute
  '/dash/settings': typeof DashSettingsRoute
  '/dash/': typeof DashIndexRoute
  '/dash/content/$ideaId': typeof DashContentIdeaIdRouteWithChildren
  '/dash/content/new': typeof DashContentNewRoute
  '/dash/posts/new': typeof DashPostsNewRoute
  '/dash/posts/scheduled': typeof DashPostsScheduledRoute
  '/dash/products/$productId': typeof DashProductsProductIdRoute
  '/dash/products/manual-import': typeof DashProductsManualImportRoute
  '/dash/content/': typeof DashContentIndexRoute
  '/dash/posts/': typeof DashPostsIndexRoute
  '/dash/products/': typeof DashProductsIndexRoute
  '/dash/content/$ideaId/edit': typeof DashContentIdeaIdEditRoute
  '/dash/posts/$postId/edit': typeof DashPostsPostIdEditRoute
  '/dash/posts/$postId/': typeof DashPostsPostIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dash'
    | '/dash/analytics'
    | '/dash/content'
    | '/dash/pages'
    | '/dash/prompts'
    | '/dash/schedule'
    | '/dash/settings'
    | '/dash/'
    | '/dash/content/$ideaId'
    | '/dash/content/new'
    | '/dash/posts/new'
    | '/dash/posts/scheduled'
    | '/dash/products/$productId'
    | '/dash/products/manual-import'
    | '/dash/content/'
    | '/dash/posts/'
    | '/dash/products/'
    | '/dash/content/$ideaId/edit'
    | '/dash/posts/$postId/edit'
    | '/dash/posts/$postId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dash/analytics'
    | '/dash/pages'
    | '/dash/prompts'
    | '/dash/schedule'
    | '/dash/settings'
    | '/dash'
    | '/dash/content/$ideaId'
    | '/dash/content/new'
    | '/dash/posts/new'
    | '/dash/posts/scheduled'
    | '/dash/products/$productId'
    | '/dash/products/manual-import'
    | '/dash/content'
    | '/dash/posts'
    | '/dash/products'
    | '/dash/content/$ideaId/edit'
    | '/dash/posts/$postId/edit'
    | '/dash/posts/$postId'
  id:
    | '__root__'
    | '/'
    | '/dash'
    | '/dash/analytics'
    | '/dash/content'
    | '/dash/pages'
    | '/dash/prompts'
    | '/dash/schedule'
    | '/dash/settings'
    | '/dash/'
    | '/dash/content/$ideaId'
    | '/dash/content/new'
    | '/dash/posts/new'
    | '/dash/posts/scheduled'
    | '/dash/products/$productId'
    | '/dash/products/manual-import'
    | '/dash/content/'
    | '/dash/posts/'
    | '/dash/products/'
    | '/dash/content/$ideaId/edit'
    | '/dash/posts/$postId/edit'
    | '/dash/posts/$postId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashRoute: typeof DashRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dash': {
      id: '/dash'
      path: '/dash'
      fullPath: '/dash'
      preLoaderRoute: typeof DashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dash/': {
      id: '/dash/'
      path: '/'
      fullPath: '/dash/'
      preLoaderRoute: typeof DashIndexRouteImport
      parentRoute: typeof DashRoute
    }
    '/dash/settings': {
      id: '/dash/settings'
      path: '/settings'
      fullPath: '/dash/settings'
      preLoaderRoute: typeof DashSettingsRouteImport
      parentRoute: typeof DashRoute
    }
    '/dash/schedule': {
      id: '/dash/schedule'
      path: '/schedule'
      fullPath: '/dash/schedule'
      preLoaderRoute: typeof DashScheduleRouteImport
      parentRoute: typeof DashRoute
    }
    '/dash/prompts': {
      id: '/dash/prompts'
      path: '/prompts'
      fullPath: '/dash/prompts'
      preLoaderRoute: typeof DashPromptsRouteImport
      parentRoute: typeof DashRoute
    }
    '/dash/pages': {
      id: '/dash/pages'
      path: '/pages'
      fullPath: '/dash/pages'
      preLoaderRoute: typeof DashPagesRouteImport
      parentRoute: typeof DashRoute
    }
    '/dash/content': {
      id: '/dash/content'
      path: '/content'
      fullPath: '/dash/content'
      preLoaderRoute: typeof DashContentRouteImport
      parentRoute: typeof DashRoute
    }
    '/dash/analytics': {
      id: '/dash/analytics'
      path: '/analytics'
      fullPath: '/dash/analytics'
      preLoaderRoute: typeof DashAnalyticsRouteImport
      parentRoute: typeof DashRoute
    }
    '/dash/products/': {
      id: '/dash/products/'
      path: '/products'
      fullPath: '/dash/products/'
      preLoaderRoute: typeof DashProductsIndexRouteImport
      parentRoute: typeof DashRoute
    }
    '/dash/posts/': {
      id: '/dash/posts/'
      path: '/posts'
      fullPath: '/dash/posts/'
      preLoaderRoute: typeof DashPostsIndexRouteImport
      parentRoute: typeof DashRoute
    }
    '/dash/content/': {
      id: '/dash/content/'
      path: '/'
      fullPath: '/dash/content/'
      preLoaderRoute: typeof DashContentIndexRouteImport
      parentRoute: typeof DashContentRoute
    }
    '/dash/products/manual-import': {
      id: '/dash/products/manual-import'
      path: '/products/manual-import'
      fullPath: '/dash/products/manual-import'
      preLoaderRoute: typeof DashProductsManualImportRouteImport
      parentRoute: typeof DashRoute
    }
    '/dash/products/$productId': {
      id: '/dash/products/$productId'
      path: '/products/$productId'
      fullPath: '/dash/products/$productId'
      preLoaderRoute: typeof DashProductsProductIdRouteImport
      parentRoute: typeof DashRoute
    }
    '/dash/posts/scheduled': {
      id: '/dash/posts/scheduled'
      path: '/posts/scheduled'
      fullPath: '/dash/posts/scheduled'
      preLoaderRoute: typeof DashPostsScheduledRouteImport
      parentRoute: typeof DashRoute
    }
    '/dash/posts/new': {
      id: '/dash/posts/new'
      path: '/posts/new'
      fullPath: '/dash/posts/new'
      preLoaderRoute: typeof DashPostsNewRouteImport
      parentRoute: typeof DashRoute
    }
    '/dash/content/new': {
      id: '/dash/content/new'
      path: '/new'
      fullPath: '/dash/content/new'
      preLoaderRoute: typeof DashContentNewRouteImport
      parentRoute: typeof DashContentRoute
    }
    '/dash/content/$ideaId': {
      id: '/dash/content/$ideaId'
      path: '/$ideaId'
      fullPath: '/dash/content/$ideaId'
      preLoaderRoute: typeof DashContentIdeaIdRouteImport
      parentRoute: typeof DashContentRoute
    }
    '/dash/posts/$postId/': {
      id: '/dash/posts/$postId/'
      path: '/posts/$postId'
      fullPath: '/dash/posts/$postId/'
      preLoaderRoute: typeof DashPostsPostIdIndexRouteImport
      parentRoute: typeof DashRoute
    }
    '/dash/posts/$postId/edit': {
      id: '/dash/posts/$postId/edit'
      path: '/posts/$postId/edit'
      fullPath: '/dash/posts/$postId/edit'
      preLoaderRoute: typeof DashPostsPostIdEditRouteImport
      parentRoute: typeof DashRoute
    }
    '/dash/content/$ideaId/edit': {
      id: '/dash/content/$ideaId/edit'
      path: '/edit'
      fullPath: '/dash/content/$ideaId/edit'
      preLoaderRoute: typeof DashContentIdeaIdEditRouteImport
      parentRoute: typeof DashContentIdeaIdRoute
    }
  }
}

interface DashContentIdeaIdRouteChildren {
  DashContentIdeaIdEditRoute: typeof DashContentIdeaIdEditRoute
}

const DashContentIdeaIdRouteChildren: DashContentIdeaIdRouteChildren = {
  DashContentIdeaIdEditRoute: DashContentIdeaIdEditRoute,
}

const DashContentIdeaIdRouteWithChildren =
  DashContentIdeaIdRoute._addFileChildren(DashContentIdeaIdRouteChildren)

interface DashContentRouteChildren {
  DashContentIdeaIdRoute: typeof DashContentIdeaIdRouteWithChildren
  DashContentNewRoute: typeof DashContentNewRoute
  DashContentIndexRoute: typeof DashContentIndexRoute
}

const DashContentRouteChildren: DashContentRouteChildren = {
  DashContentIdeaIdRoute: DashContentIdeaIdRouteWithChildren,
  DashContentNewRoute: DashContentNewRoute,
  DashContentIndexRoute: DashContentIndexRoute,
}

const DashContentRouteWithChildren = DashContentRoute._addFileChildren(
  DashContentRouteChildren,
)

interface DashRouteChildren {
  DashAnalyticsRoute: typeof DashAnalyticsRoute
  DashContentRoute: typeof DashContentRouteWithChildren
  DashPagesRoute: typeof DashPagesRoute
  DashPromptsRoute: typeof DashPromptsRoute
  DashScheduleRoute: typeof DashScheduleRoute
  DashSettingsRoute: typeof DashSettingsRoute
  DashIndexRoute: typeof DashIndexRoute
  DashPostsNewRoute: typeof DashPostsNewRoute
  DashPostsScheduledRoute: typeof DashPostsScheduledRoute
  DashProductsProductIdRoute: typeof DashProductsProductIdRoute
  DashProductsManualImportRoute: typeof DashProductsManualImportRoute
  DashPostsIndexRoute: typeof DashPostsIndexRoute
  DashProductsIndexRoute: typeof DashProductsIndexRoute
  DashPostsPostIdEditRoute: typeof DashPostsPostIdEditRoute
  DashPostsPostIdIndexRoute: typeof DashPostsPostIdIndexRoute
}

const DashRouteChildren: DashRouteChildren = {
  DashAnalyticsRoute: DashAnalyticsRoute,
  DashContentRoute: DashContentRouteWithChildren,
  DashPagesRoute: DashPagesRoute,
  DashPromptsRoute: DashPromptsRoute,
  DashScheduleRoute: DashScheduleRoute,
  DashSettingsRoute: DashSettingsRoute,
  DashIndexRoute: DashIndexRoute,
  DashPostsNewRoute: DashPostsNewRoute,
  DashPostsScheduledRoute: DashPostsScheduledRoute,
  DashProductsProductIdRoute: DashProductsProductIdRoute,
  DashProductsManualImportRoute: DashProductsManualImportRoute,
  DashPostsIndexRoute: DashPostsIndexRoute,
  DashProductsIndexRoute: DashProductsIndexRoute,
  DashPostsPostIdEditRoute: DashPostsPostIdEditRoute,
  DashPostsPostIdIndexRoute: DashPostsPostIdIndexRoute,
}

const DashRouteWithChildren = DashRoute._addFileChildren(DashRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashRoute: DashRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
